### ISSUE TITLE
Missing libgcc_s_dw2-1.dll message after running the latest build with grplugin..

### ISSUE THREAD

**Issue by raydvard** [IceNinjaman/CoD4X17a_testing#51]
Hello,

When I run the latest build 2998 with grplugin on windows it gives me error that: Missing libgcc_s_dw2-1.dll and gameranger plugin also doesn't start. But when I copy the libgcc_s_dw2-1.dll from mingw compiler's bin folder and paste it in the cod4 main directory then no such error occurs.  Please solve this error.

Thanks.

**Comment by uGiFarukh** [comment]
I am also having the same problem. Please fix this issue.
